""" Configuration file """

CONFIG = {
    "SEED": 7,
    "K_FOLD": 5,
    "EPOCHS": 1000,
    "LEARNING_RATE": 1e-4,
    "TEST_SIZE": 0.3,
    "MATRIX_SIZE": (8, 10),
    "FIG_SIZE": (10, 6),
    "LEGEND_SIZE": 14,
    "TICK_SIZE": 16,
    "LABEL_SIZE": 18,
    "TITLE_SIZE": 20,
    "SUP_TITLE_SIZE": 24,
    "GPU": "cuda:0",
    "CHROMOSOME_COLORS": ["#8100FF", "#21918C"],
    "NUMERICAL_COLUMNS": [
        "Age",
        "Weight",
        "Height",
        "BMI",
        "Population Density"
    ],
}


CLINICAL_ATTRIBUTES = {
    "Personal information": {
        "color": "#9564BF",
        "attributes": [
            "Age",
            "Sex",
            "Blood type",
            "Rh type",
            "Weight",
            "Height",
            "BMI",
        ]
    },
    "Geographical": {
        "color": "#FF7F00",
        "attributes": [
            "Nationality",
            "Province",
            "Population Density",
            "Country of birth",
        ],
    },
    "Socioeconomic": {
        "color": "#D8241F",
        "attributes": [
            "Educational level",
            "Occupational situation",
            "Health System",
        ],
    },
    "Ethnicity": {
        "color": "#24A221",
        "attributes": [
            "Ethnicity",
        ],
    },
    "Health Habits": {
        "color": "#00BED1",
        "attributes": [
            "Tobacco Consumption",
            "Daily cigars",
            "More than 100 cigars",
            "Alcohol Consumption",
            "Marijuana",
            "Cocaine",
            "Pasta Base",
            "Heroin",
            "Hallucinogens",
            "Some other drug",
            "Drug DK/NA/REF",
        ],
    },
    "Comorbidities": {
        "color": "#BCBF00",
        "attributes": [
            "Diabetes",
            "Coronary atherosclerosis",
            "Hypertension",
            "Vascular accident",
            "Heart problem",
            "Dialysis",
            "Hepatitis",
            "Anemia",
            "Asthma",
            "Cystic fibrosis",
            "Pulmonary fibrosis",
            "Pulmonary condition",
            "Cancer",
            "Condition that affects the brain",
            "HIV",
            "Tuberculosis",
            "Weakened immune system",
            "Mental health problems",
            "High cholesterol",
            "Obesity",
            "Ulcerative colitis or Crohn's disease",
            "Rheumatoid arthritis",
            "Lupus",
            "Other rheumatoid diseases",
            "Other chronic diseases",
        ],
    },
    "Cancer": {
        "color": "#8D5649",
        "attributes": [
            "Colon and straight cancer",
            "Endometrial cancer",
            "Pancreatic cancer",
            "Prostate cancer",
            "Lung cancer",
            "Kidney cancer",
            "Breast cancer",
            "Thyroid cancer",
            "Vesicle cancer",
        ],
    },
    "Drugs": {
        "color": "#1776B6",
        "attributes": [
            "Antidiabetic",
            "Anti-TB",
            "Antihypertensive",
            "Aspirin or clopidogrel",
            "Statin",
            "Analgesics",
            "Cough medication",
            "Inhaler",
            "Anticancer",
            "Antimalaric",
            "Antivirals",
            "Vitamins",
            "Medicinal herbs",
            "No drug",
            "Another medication",
            "Medication DK/NA/REF",
        ],
    },
}
